ci/cd:
  - .github/**

chore:
  - .gitignore

documentation:
  - LICENSE.md
  - README.md
  - ./*.md

core:
  - Core/*

driver:
  - Drivers/*

cubemx:
  - stm32f334c8t6.ioc

linker-script:
  - STM32F334C8TX_FLASH.ld
