name: stm32-dc-dc workflow

on: [push]

jobs:
  stm32-dc-dc-workflow:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get install make gcc-arm-none-eabi -y

      - name: Build
        run: cd Debug && make all

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: Debug
